# Text classification with DistilBERT


In [1]:
%%time
%pip install transformers~=4.40.0
%pip install torch==2.8.0+cpu torchvision==0.23.0+cpu torchaudio==2.8.0+cpu torchtext==0.18.0+cpu --index-url https://download.pytorch.org/whl/cpu

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


Looking in indexes: https://download.pytorch.org/whl/cpu
Note: you may need to restart the kernel to use updated packages.
CPU times: total: 78.1 ms
Wall time: 5.72 s



[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
%pip install tf-keras

  Obtaining dependency information for tf-keras from https://files.pythonhosted.org/packages/85/6b/d9a8202bfe5c9e3b078cf550bafab962aa9d6b1a1f1180f0065399d4c9b2/tf_keras-2.20.1-py3-none-any.whl.metadata
  Using cached tf_keras-2.20.1-py3-none-any.whl.metadata (1.8 kB)
Using cached tf_keras-2.20.1-py3-none-any.whl (1.7 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
from transformers import pipeline
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer
import torch
from transformers import GPT2LMHeadModel, GPT2Tokenizer

def warn(*args, **kwargs):
    pass

import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

D:\GitHub\IBM-AI-Engineering-Professional-Certificate\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

In [5]:
text =  "Congratulations! You've won a free ticket to the Bahamas. Reply WIN to claim."

inputs = tokenizer(text, return_tensors='pt')
print(inputs)

{'input_ids': tensor([[  101, 23156,   999,  2017,  1005,  2310,  2180,  1037,  2489,  7281,
          2000,  1996, 17094,  1012,  7514,  2663,  2000,  4366,  1012,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [6]:
with torch.no_grad():
    outputs = model(**inputs)

In [7]:
print(outputs)

SequenceClassifierOutput(loss=None, logits=tensor([[-3.9954,  4.3336]]), hidden_states=None, attentions=None)


In [8]:
logits = outputs.logits
print(logits)

tensor([[-3.9954,  4.3336]])


In [9]:
logits.shape

torch.Size([1, 2])

In [10]:
probabilities = torch.softmax(logits, dim=-1)
probabilities

tensor([[2.4134e-04, 9.9976e-01]])

In [11]:
predicted_class = torch.argmax(probabilities, dim=-1)
print(predicted_class)

tensor([1])


In [12]:
labels = ["NEGATIVE", "POSITIVE"]
predicted_label = labels[predicted_class]
predicted_label

'POSITIVE'

# Text generation with GPT-2


In [13]:
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")

In [14]:
prompt = "once upon a time"
inputs = tokenizer(prompt, return_tensors='pt')
print(inputs)

{'input_ids': tensor([[27078,  2402,   257,   640]]), 'attention_mask': tensor([[1, 1, 1, 1]])}


In [15]:
output_ids = model.generate(
    inputs.input_ids,
    attention_mask=inputs.attention_mask,
    pad_token_id=tokenizer.eos_token_id,
    max_length=50,
    num_return_sequences=1
)
output_ids

tensor([[27078,  2402,   257,   640,    11,   290,   314,  1101,   407,  1654,
           611,   340,   338,   257, 21083,   393,   407,    13,   198,   198,
            40,  1101,   407,  1654,   611,   340,   338,   257, 21083,   393,
           407,    13,   314,  1101,   407,  1654,   611,   340,   338,   257,
         21083,   393,   407,    13,   314,  1101,   407,  1654,   611,   340]])

In [16]:
with torch.no_grad():
    outputs = model(**inputs)
outputs

CausalLMOutputWithCrossAttentions(loss=None, logits=tensor([[[-30.1669, -29.4417, -32.9058,  ..., -38.2625, -36.2816, -30.8976],
         [-25.3130, -22.1363, -29.5302,  ..., -35.3004, -28.1749, -25.7128],
         [-81.5708, -78.1417, -83.7729,  ..., -89.1826, -82.3724, -79.2839],
         [-64.3918, -62.5890, -72.1425,  ..., -74.7520, -71.3967, -67.3438]]]), past_key_values=((tensor([[[[-1.6328,  1.7646,  0.5022,  ..., -0.8582, -0.4570,  0.9253],
          [-1.8341,  2.1130,  2.3510,  ..., -0.4822, -1.0945,  1.5408],
          [-2.3145,  2.7101,  1.5073,  ..., -0.5781, -1.9292,  2.2634],
          [-2.9968,  2.8426,  2.8197,  ..., -0.2256, -2.4446,  1.9452]],

         [[-0.5509,  0.5419, -0.0377,  ...,  0.6399,  1.9697, -0.6283],
          [-1.3115, -0.7469, -0.8230,  ...,  2.3210,  3.2909, -0.1097],
          [-0.7140, -1.6105, -2.9748,  ..., -1.6920,  4.4462,  0.1892],
          [-0.4404,  0.2157, -2.1341,  ..., -2.1349,  3.6455, -1.5257]],

         [[ 0.3968, -1.2266,  0.7770,  

In [17]:
generated_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)
generated_text

"once upon a time, and I'm not sure if it's a coincidence or not.\n\nI'm not sure if it's a coincidence or not. I'm not sure if it's a coincidence or not. I'm not sure if it"

In [18]:
classifier = pipeline(
    'text-classification',
    model='distilbert-base-uncased-finetuned-sst-2-english'
)
result = classifier("Congratulations! You've won a free ticket to the Bahamas. Reply WIN to claim.")
result

[{'label': 'POSITIVE', 'score': 0.9997586607933044}]

In [19]:
classifier = pipeline("text-classification",
                      model="papluca/xlm-roberta-base-language-detection")
result = classifier("Bonjour, comment ça va?")
result

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


[{'label': 'fr', 'score': 0.9934879541397095}]

In [20]:
generator = pipeline(
    'text-generation',
    model='gpt2'
)

prompt = 'Once upon a time'
result = generator(
    prompt,
    max_length=50,
    num_return_sequences=1,
    truncation=True
)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [21]:
result

[{'generated_text': "Once upon a time, all was well for the Emperor's Army. He seemed content to rest until a time, where he could rise to his appointed position. And so they began their day of testing.\n\nThe next night, in one of"}]

In [22]:
result[0]

{'generated_text': "Once upon a time, all was well for the Emperor's Army. He seemed content to rest until a time, where he could rise to his appointed position. And so they began their day of testing.\n\nThe next night, in one of"}

In [23]:
result[0]['generated_text']

"Once upon a time, all was well for the Emperor's Army. He seemed content to rest until a time, where he could rise to his appointed position. And so they began their day of testing.\n\nThe next night, in one of"

In [24]:
generator = pipeline(
    'text2text-generation',
    model='t5-small'
)
prompt = 'translate English to French: How are you?'
result = generator(
    prompt,
    max_length=50,
    num_return_sequences=1
)
result

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


[{'generated_text': 'Comment êtes-vous?'}]

In [27]:
fill_mask = pipeline(
    'fill-mask',
    model='bert-base-uncased'
)

prompt = "The capital of France is [MASK]."
result = fill_mask(prompt)
result

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


[{'score': 0.41678985953330994,
  'token': 3000,
  'token_str': 'paris',
  'sequence': 'the capital of france is paris.'},
 {'score': 0.07141648977994919,
  'token': 22479,
  'token_str': 'lille',
  'sequence': 'the capital of france is lille.'},
 {'score': 0.06339266151189804,
  'token': 10241,
  'token_str': 'lyon',
  'sequence': 'the capital of france is lyon.'},
 {'score': 0.0444474071264267,
  'token': 16766,
  'token_str': 'marseille',
  'sequence': 'the capital of france is marseille.'},
 {'score': 0.03029717691242695,
  'token': 7562,
  'token_str': 'tours',
  'sequence': 'the capital of france is tours.'}]