In [1]:
import torch

In [2]:
w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(-1.0, requires_grad=True)

def forward(x):
    yhat = w * x + b
    return yhat

x = torch.tensor([1.0])
yhat = forward(x)
print(yhat)

tensor([1.], grad_fn=<AddBackward0>)


In [5]:
x = torch.tensor([[1.0], [2.0]])
yhat = forward(x)
print(yhat)

tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


In [7]:
from torch.nn import Linear
torch.manual_seed(1)
lr = Linear(in_features=1, out_features=1, bias=True)
list(lr.parameters())

[Parameter containing:
 tensor([[0.5153]], requires_grad=True),
 Parameter containing:
 tensor([-0.4414], requires_grad=True)]

In [8]:
lr.state_dict()

OrderedDict([('weight', tensor([[0.5153]])), ('bias', tensor([-0.4414]))])

In [9]:
lr.state_dict().keys()

odict_keys(['weight', 'bias'])

In [10]:
lr.state_dict().values()

odict_values([tensor([[0.5153]]), tensor([-0.4414])])

In [11]:
lr.weight

Parameter containing:
tensor([[0.5153]], requires_grad=True)

In [12]:
lr.bias

Parameter containing:
tensor([-0.4414], requires_grad=True)

In [13]:
x = torch.tensor([1.0])
yhat = lr(x)
yhat

tensor([0.0739], grad_fn=<ViewBackward0>)

In [15]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print(yhat)

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward0>)


In [17]:
from torch import nn

class LR(nn.Module):
    def __init__(self, input_size, output_size):
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):
        out = self.linear(x)
        return out

lr = LR(1, 1)
list(lr.parameters())

[Parameter containing:
 tensor([[-0.9414]], requires_grad=True),
 Parameter containing:
 tensor([0.5997], requires_grad=True)]

In [18]:
print(lr.linear)

Linear(in_features=1, out_features=1, bias=True)


In [20]:
x = torch.tensor([[1.0]])
yhat = lr(x)
print(yhat)

tensor([[-0.3417]], grad_fn=<AddmmBackward0>)


In [22]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print(yhat)

tensor([[-0.3417],
        [-1.2832]], grad_fn=<AddmmBackward0>)


In [24]:
print(lr.state_dict())
print(lr.state_dict().keys())
print(lr.state_dict().values())

OrderedDict({'linear.weight': tensor([[-0.9414]]), 'linear.bias': tensor([0.5997])})
odict_keys(['linear.weight', 'linear.bias'])
odict_values([tensor([[-0.9414]]), tensor([0.5997])])


In [25]:
x = torch.tensor([[1.0], [2.0], [3.0]])
x=torch.tensor([[1.0],[2.0],[3.0]])
lr1=LR(1,1)
yhat=lr1(x)
print(yhat)

tensor([[ 0.3030],
        [ 0.0973],
        [-0.1084]], grad_fn=<AddmmBackward0>)
