In [2]:
from torch import nn
import torch
torch.manual_seed(1)

In [4]:
X = torch.tensor([[1.0, 1.0],
                  [1.0, 2.0],
                  [1.0, 3.0]])

model = nn.Linear(in_features=2, out_features=1)

yhat = model(X)
print(yhat)

tensor([[ 0.0903],
        [-0.5754],
        [-1.2411]], grad_fn=<AddmmBackward0>)


In [5]:
class linear_regression(nn.Module):
    def __init__(self, input_size, output_size):
        super(linear_regression, self).__init__()

        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):
        yhat = self.linear(x)
        return yhat

In [6]:
model = linear_regression(2, 1)

In [7]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.1455,  0.3597]], requires_grad=True),
 Parameter containing:
 tensor([0.0983], requires_grad=True)]

In [8]:
model.state_dict()

OrderedDict([('linear.weight', tensor([[-0.1455,  0.3597]])),
             ('linear.bias', tensor([0.0983]))])

In [9]:
yhat = model(X)
print(yhat)

tensor([[0.3126],
        [0.6723],
        [1.0320]], grad_fn=<AddmmBackward0>)
