In [17]:
from torch import nn
import torch
torch.manual_seed(1)

In [18]:
class linear_regression(nn.Module):
    def __init__(self, input_size, output_size):
        super(linear_regression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    def forward(self, x):
        yhat = self.linear(x)
        return yhat

In [19]:
model = linear_regression(1, 10)


In [ ]:
x = torch.tensor([1.0])
model(x)

In [4]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.5153],
         [-0.4414],
         [-0.1939],
         [ 0.4694],
         [-0.9414],
         [ 0.5997],
         [-0.2057],
         [ 0.5087],
         [ 0.1390],
         [-0.1224]], requires_grad=True),
 Parameter containing:
 tensor([ 0.2774,  0.0493,  0.3652, -0.3897, -0.0729, -0.0900,  0.1449, -0.0040,
          0.8742,  0.3112], requires_grad=True)]

In [13]:
x=torch.tensor([[1.0]])
yhat=model(x)


In [16]:
print(yhat)

tensor([[ 0.7926, -0.3920,  0.1714,  0.0797, -1.0143,  0.5097, -0.0608,  0.5047,
          1.0132,  0.1887]], grad_fn=<AddmmBackward0>)


In [21]:
X=torch.tensor([[1.0],[1.0],[3.0]])
Yhat=model(X)
Yhat.detach().numpy()

array([[ 0.7926241 , -0.39204645,  0.17136669,  0.07966793, -1.0143456 ,
         0.5096899 , -0.06078136,  0.50474906,  1.0131837 ,  0.18874598],
       [ 0.7926241 , -0.39204645,  0.17136669,  0.07966793, -1.0143456 ,
         0.5096899 , -0.06078136,  0.50474906,  1.0131837 ,  0.18874598],
       [ 1.8231505 , -1.2748029 , -0.21635628,  1.0184058 , -2.8972194 ,
         1.7091244 , -0.47223198,  1.5222368 ,  1.2912177 , -0.05614233]],
      dtype=float32)