In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import pandas as pd

In [3]:
twoD_list = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
twoD_tensor = torch.tensor(twoD_list)
print(twoD_tensor)

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])


In [5]:
print(twoD_tensor.ndimension())
print(twoD_tensor.size())
print(twoD_tensor.shape)
print(twoD_tensor.numel())

2
torch.Size([3, 3])
torch.Size([3, 3])
9


In [6]:
twoD_numpy = twoD_tensor.numpy()
print(twoD_numpy)
print(twoD_numpy.dtype)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
int64


In [7]:
new_twoD_tensor = torch.from_numpy(twoD_numpy)
print(new_twoD_tensor)
print(new_twoD_tensor.dtype)

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])
torch.int64


In [8]:
df = pd.DataFrame({'a':[11,21,31],'b':[12,22,312]})
print(df.values)
print(df.values.dtype)

[[ 11  12]
 [ 21  22]
 [ 31 312]]
int64


In [9]:
new_tensor = torch.from_numpy(df.values)
print(new_tensor)
print(new_tensor.dtype)

tensor([[ 11,  12],
        [ 21,  22],
        [ 31, 312]])
torch.int64


In [10]:
df = pd.DataFrame({'A':[11, 33, 22],'B':[3, 3, 2]})
new_tensor = torch.from_numpy(df.values)
print(new_tensor)

tensor([[11,  3],
        [33,  3],
        [22,  2]])


In [16]:
tensor_example = torch.tensor([[11, 12, 13],
                               [21, 22, 23],
                               [31, 32, 33]])
print(tensor_example[0, 0])
print(tensor_example[0][0])

tensor(11)
tensor(11)


In [19]:
print(tensor_example[0, 0:3])
print(tensor_example[0][0:3])

tensor([11, 12, 13])
tensor([11, 12, 13])


In [20]:
print(tensor_example[0:3, 0])

tensor([11, 21, 31])


In [21]:
tensor_ques = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])

tensor_ques[1:3, 1] = 0
print(tensor_ques)

tensor([[11, 12, 13],
        [21,  0, 23],
        [31,  0, 33]])


In [22]:
X = torch.tensor([[1, 0],[0, 1]])
Y = torch.tensor([[2, 1],[1, 2]])

w = X + Y
print(w)

tensor([[3, 1],
        [1, 3]])


In [23]:
Y = torch.tensor([[2, 1], [1, 2]])
two_Y = 2 * Y
print(two_Y)

tensor([[4, 2],
        [2, 4]])


In [24]:
X = torch.tensor([[1, 0], [0, 1]])
Y = torch.tensor([[2, 1], [1, 2]])
X_times_Y = X * Y
print(X_times_Y)

tensor([[2, 0],
        [0, 2]])


In [25]:
A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])
A_times_B = torch.mm(A, B)
print(A_times_B)

tensor([[0, 2],
        [0, 2]])
